[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment to use this redirect for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200